CREATE OR REPLACE TABLE STAGING.STG_BRAND_MARKETING(APPROVAL_STATUS_ID int,
ASSET_DESCRIPTION varchar(400)
,ASSET_TYPE_ID NUMBER(30,0)
,BILLING_MONTH_ID varchar(100)
,BRAND_ID NUMBER(30,0)
,DATE_CREATED TIMESTAMPTZ
,END_DATE TIMESTAMPTZ
,IS_INACTIVE varchar(400)
,LAST_MODIFIED_DATE TIMESTAMPTZ
,MERCH_MARKETING_CONTACT_ID NUMBER(30,0)
,PARENT_ID NUMBER(30,0)
,START_DATE TIMESTAMPTZ
,TOTAL_COST NUMBER(30,0)
,VENDOR_FUNDING__BRAND_MARKE_EX NUMBER(30,0)
,VENDOR_FUNDING__BRAND_MARKE_ID NUMBER(30,0)
,VENDOR_FUNDING__BRAND_MARKE_NA varchar(400)
,VENDOR_FUNDING_ITEM varchar(400)
,MM_EMAIL varchar(400)
,MM_NAME varchar(400)
,JOBTITLE varchar(400)
,BRAND_RECORDS_NAME varchar(400)
,BILLING_CUSTOMER_ID NUMBER(30,0)
,BILLING_VENDOR_ID NUMBER(30,0)
,COMPANYNAME varchar(400)
,CUSTOMER_EMAIL varchar(400)
,CUSTOMER_NAME varchar(400)
,billing_method varchar(400)
,ODS_PROCESSED_DATE TIMESTAMPTZ
,BRANDEMAIL varchar(100)

CREATE OR REPLACE TABLE ODS.BRAND_MARKETING(APPROVAL_STATUS_ID int,
ASSET_DESCRIPTION varchar(400)
,ASSET_TYPE_ID NUMBER(30,0)
,BILLING_MONTH_ID varchar(100)
,BRAND_ID NUMBER(30,0)
,DATE_CREATED TIMESTAMPTZ
,END_DATE TIMESTAMPTZ
,IS_INACTIVE varchar(400)
,LAST_MODIFIED_DATE TIMESTAMPTZ
,MERCH_MARKETING_CONTACT_ID NUMBER(30,0)
,PARENT_ID NUMBER(30,0)
,START_DATE TIMESTAMPTZ
,TOTAL_COST NUMBER(30,0)
,VENDOR_FUNDING__BRAND_MARKE_EX NUMBER(30,0)
,VENDOR_FUNDING__BRAND_MARKE_ID NUMBER(30,0)
,VENDOR_FUNDING__BRAND_MARKE_NA varchar(400)
,VENDOR_FUNDING_ITEM varchar(400)
,MM_EMAIL varchar(400)
,MM_NAME varchar(400)
,JOBTITLE varchar(400)
,BRAND_RECORDS_NAME varchar(400)
,BILLING_CUSTOMER_ID NUMBER(30,0)
,BILLING_VENDOR_ID NUMBER(30,0)
,COMPANYNAME varchar(400)
,CUSTOMER_EMAIL varchar(400)
,CUSTOMER_NAME varchar(400)
,billing_method varchar(400)
,ODS_PROCESSED_DATE TIMESTAMPTZ,
BRANDEMAIL varchar(100))

--- Adjust transaction data for additional fields 
ALTER TABLE TM_IGLOO_ODS_STG.ods."TRANSACTIONS" 
ADD	BRAND_MARKETING_ID number(35);

ALTER TABLE TM_IGLOO_ODS_STG.staging.STG_BRAND_MARKETING 
ADD BRANDEMAIL varchar(200);

ALTER TABLE TM_IGLOO_ODS_STG.ods.BRAND_MARKETING 
ADD BRANDEMAIL varchar(200);

SELECT * FROM ods.BRAND_MARKETING 



SELECT  * FROM STAGING.stg_brand_marketing br
LEFT OUTER JOIN ods.brand_marketing bm ON br.VENDOR_FUNDING__BRAND_MARKE_ID = bm.VENDOR_FUNDING__BRAND_MARKE_ID
WHERE bm.VENDOR_FUNDING__BRAND_MARKE_ID IS NULL 


TRUNCATE ODS.BRAND_MARKETING

GRANT ALL ON  ODS.BRAND_MARKETING  TO ods_stg_sa

GRANT ALL ON  ODS.BRAND_MARKETING   TO FINANCE_BUS


SELECT * FROM staging.STG_BRAND_MARKETING 



SELECT * FROM ods.BRAND_MARKETING 


insert into ods.transactions (TRAN_TYPE,TRAN_SUB_TYPE,TRAN_DATE,ORDER_TYPE,COMPANY_ID,CREATED_AT,TRAN_SUB_TYPE_ID,TRAN_GL_DATE,TRAN_AMT,BRAND_MARKETING_ID)

SELECT 300,'Brand Marketing Fees',bm.START_DATE,'order','1',bm.ODS_PROCESSED_DATE,112,bm.START_DATE ::date ,bm.TOTAL_COST, bm.VENDOR_FUNDING__BRAND_MARKE_ID  
FROM ods.brand_marketing bm
FULL OUTER JOIN (SELECT DISTINCT tr.BRAND_MARKETING_ID FROM ods."TRANSACTIONS" tr ) trn ON trn.brand_marketing_id = bm.VENDOR_FUNDING__BRAND_MARKE_ID 
WHERE trn.brand_marketing_iD IS NULL AND bm.START_DATE IS NOT null

SELECT * FROM ods.BRAND_MARKETING 


SELECT tr.TRAN_GL_DATE, bm.BRAND_RECORDS_NAME ,bm.BILLING_METHOD,
COALESCE( bm.BILLING_CUSTOMER_ID ,bm.BILLING_VENDOR_ID) AS vend_cust, bm.VENDOR_FUNDING_ITEM ,bm.ASSET_DESCRIPTION ,bm.MM_EMAIL ,bm.START_DATE ,bm.END_DATE ,bm.BILLING_MONTH_ID,tr.TRAN_AMT  FROM ods."TRANSACTIONS" tr 
LEFT JOIN ods.BRAND_MARKETING bm ON bm.VENDOR_FUNDING__BRAND_MARKE_ID = tr.BRAND_MARKETING_ID 
WHERE tr.TRAN_SUB_TYPE_ID =112 	 AND tr."TRAN_GL_DATE" BETWEEN $P{start_date} AND $P{end_date}

