CREATE OR REPLACE TABLE STAGING.STG_BRAND_MARKETING(
ASSET_DESCRIPTION varchar(400)
,ASSET_TYPE_ID NUMBER(30,0)
,BILLING_MONTH_ID NUMBER(30,0)
,BRAND_ID NUMBER(30,0)
,DATE_CREATED TIMESTAMPTZ
,END_DATE TIMESTAMPTZ
,IS_INACTIVE varchar(400)
,LAST_MODIFIED_DATE TIMESTAMPTZ
,MERCH_MARKETING_CONTACT_ID NUMBER(30,0)
,PARENT_ID NUMBER(30,0)
,START_DATE TIMESTAMPTZ
,TOTAL_COST NUMBER(30,0)
,VENDOR_FUNDING__BRAND_MARKE_EX NUMBER(30,0)
,VENDOR_FUNDING__BRAND_MARKE_ID NUMBER(30,0)
,VENDOR_FUNDING__BRAND_MARKE_NA varchar(400)
,VENDOR_FUNDING_ITEM varchar(400)
,MM_EMAIL varchar(400)
,MM_NAME varchar(400)
,JOBTITLE varchar(400)
,BRAND_RECORDS_NAME varchar(400)
,BILLING_CUSTOMER_ID NUMBER(30,0)
,BILLING_VENDOR_ID NUMBER(30,0)
,COMPANYNAME varchar(400)
,CUSTOMER_EMAIL varchar(400)
,CUSTOMER_NAME varchar(400)
,billing_method varchar(400)
,ODS_PROCESSED_DATE TIMESTAMPTZ)

CREATE OR REPLACE TABLE ODS.BRAND_MARKETING(
ASSET_DESCRIPTION varchar(400)
,ASSET_TYPE_ID NUMBER(30,0)
,BILLING_MONTH_ID NUMBER(30,0)
,BRAND_ID NUMBER(30,0)
,DATE_CREATED TIMESTAMPTZ
,END_DATE TIMESTAMPTZ
,IS_INACTIVE varchar(400)
,LAST_MODIFIED_DATE TIMESTAMPTZ
,MERCH_MARKETING_CONTACT_ID NUMBER(30,0)
,PARENT_ID NUMBER(30,0)
,START_DATE TIMESTAMPTZ
,TOTAL_COST NUMBER(30,0)
,VENDOR_FUNDING__BRAND_MARKE_EX NUMBER(30,0)
,VENDOR_FUNDING__BRAND_MARKE_ID NUMBER(30,0)
,VENDOR_FUNDING__BRAND_MARKE_NA varchar(400)
,VENDOR_FUNDING_ITEM varchar(400)
,MM_EMAIL varchar(400)
,MM_NAME varchar(400)
,JOBTITLE varchar(400)
,BRAND_RECORDS_NAME varchar(400)
,BILLING_CUSTOMER_ID NUMBER(30,0)
,BILLING_VENDOR_ID NUMBER(30,0)
,COMPANYNAME varchar(400)
,CUSTOMER_EMAIL varchar(400)
,CUSTOMER_NAME varchar(400)
,billing_method varchar(400)
,ODS_PROCESSED_DATE TIMESTAMPTZ )



SELECT  * FROM STAGING.stg_brand_marketing br
LEFT OUTER JOIN ods.brand_marketing bm ON br.VENDOR_FUNDING__BRAND_MARKE_ID = bm.VENDOR_FUNDING__BRAND_MARKE_ID
WHERE bm.VENDOR_FUNDING__BRAND_MARKE_ID IS NULL 


TRUNCATE staging.STG_BRAND_MARKETING 

GRANT ALL ON  STAGING.STG_BRAND_MARKETING  TO ods_stg_sa

GRANT ALL ON  ODS.BRAND_MARKETING  TO ods_stg_sa


SELECT * FROM staging.STG_BRAND_MARKETING 


insert into ods.transactions (TRAN_TYPE,TRAN_SUB_TYPE,TRAN_DATE,ORDER_TYPE,COMPANY_ID,CREATED_AT,TRAN_SUB_TYPE_ID,TRAN_GL_DATE,TRAN_AMT)

SELECT 300,'Brand Marketing Fees',bm.START_DATE,'order','1',bm.ODS_PROCESSED_DATE,112,bm.START_DATE ::date ,bm.TOTAL_COST  FROM ods.brand_marketing bm

SELECT * FROM ods.BRAND_MARKETING 

SELECT * FROM ods.NS_COSTADJ_DETAIL 